{exec} = require 'child_process'

task 'watch', 'Build files', ->
  exec 'coffee -o app/client/js/ -cw app/client/coffee/', (err, stdout, stderr) ->
    console.log stdout
    throw err if err
    console.log stdout + stderr